version: "3.1"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wg_planner
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql # Persistent volume for MySQL data
      - ./init_scripts/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql # Run schema.sql during initialization

  backend:
    build: .
    container_name: node_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_database
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
